.PHONY: venv lint pretty start start-db build stop test migrations migrate

venv:
	python -m venv venv
	.\venv\Scripts\pip install -r requirements.txt

start:
	docker compose -f docker-compose.yml up --force-recreate --remove-orphans

stop:
	docker compose -f docker-compose.yml down

build:
	docker compose -f docker-compose.yml build

start-db:
	docker compose -f docker-compose.yml up -d db

migrations:
	alembic revision --autogenerate

migrate:
	alembic upgrade head
